services:
  - type: web
    name: pythonlogin-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 # Using a stable version, or 3.12.0
      - key: DATABASE_URL
        value: postgresql://inventory_db_srkn_user:Ll4V8W4gZlH8hZTcsRDZb4U2Cq4nul3v@dpg-d7qdophkh4rs73fgjfgg-a.oregon-postgres.render.com/inventory_db_srkn

  - type: static
    name: pythonlogin-driver
    rootDir: frontend_driver
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://pythonlogin-backend.onrender.com

  - type: static
    name: pythonlogin-passenger
    rootDir: frontend_passenger
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://pythonlogin-backend.onrender.com
